# Generated by Django 2.2.20 on 2021-04-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamentName', models.CharField(max_length=30, verbose_name='Название турнира')),
                ('team_1', models.CharField(max_length=30, verbose_name='Первая команда')),
                ('team_2', models.CharField(max_length=30, verbose_name='Вторая команда')),
                ('map', models.CharField(max_length=30, verbose_name='Карта')),
                ('date', models.DateTimeField(verbose_name='Время матча')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
