# Generated by Django 2.2.20 on 2021-04-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='map',
            field=models.CharField(choices=[('Mirage', 'de_mirage'), ('Dust2', 'de_dust2'), ('Vertigo', 'de_vertigo'), ('Nuke', 'de_nuke'), ('Inferno', 'de_inferno'), ('Overpass', 'de_overpass'), ('Train', 'de_train')], max_length=30, verbose_name='Карта'),
        ),
    ]
