# Generated by Django 2.2.20 on 2021-04-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20210417_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='map',
            field=models.CharField(choices=[('de_mirage', 'Mirage'), ('de_dust2', 'Dust2'), ('de_vertigo', 'Vertigo'), ('de_nuke', 'Nuke'), ('de_inferno', 'Inferno'), ('de_overpass', 'Overpass'), ('de_train', 'Train')], max_length=30, verbose_name='Карта'),
        ),
    ]
