# Generated by Django 2.2.20 on 2021-04-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_teams_teamname'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='insta',
            field=models.CharField(max_length=30, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='teams',
            name='vk',
            field=models.CharField(max_length=30, null=True, verbose_name='VK'),
        ),
    ]
