# Generated by Django 2.2.20 on 2021-04-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20210413_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='Фото'),
        ),
    ]
