# Generated by Django 2.2.20 on 2021-04-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_teams_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='insta',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='vk',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='VK'),
        ),
    ]
