# Generated by Django 2.2.20 on 2021-04-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaponName', models.CharField(max_length=30, verbose_name='Название оружия')),
                ('skinName', models.CharField(max_length=30, verbose_name='Название скина')),
                ('condition', models.CharField(max_length=15, verbose_name='Качество')),
                ('price', models.CharField(max_length=7, verbose_name='Цена')),
                ('float', models.CharField(max_length=8, verbose_name='Флоат')),
            ],
            options={
                'verbose_name': 'Маркет',
                'verbose_name_plural': 'Маркет',
            },
        ),
    ]
