# Generated by Django 2.2.20 on 2021-04-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='photo',
            field=models.TextField(blank=True, null=True, verbose_name='Фото'),
        ),
    ]
