# Generated by Django 2.2.20 on 2021-04-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_market_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='seller',
            field=models.TextField(null=True, verbose_name='Ссылка на продавца'),
        ),
    ]
