# Generated by Django 2.2.20 on 2021-04-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_market_seller_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='seller',
            field=models.TextField(null=True, verbose_name='Продавец'),
        ),
    ]
