# Generated by Django 2.2.20 on 2021-04-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='nickname',
            field=models.CharField(max_length=30, null=True, verbose_name='Ник'),
        ),
    ]
