# Generated by Django 2.2.20 on 2021-04-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_players_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='insta',
            field=models.TextField(null=True, verbose_name='Instagram-link'),
        ),
        migrations.AddField(
            model_name='players',
            name='steam',
            field=models.TextField(null=True, verbose_name='Steam-profile'),
        ),
        migrations.AddField(
            model_name='players',
            name='vk',
            field=models.TextField(null=True, verbose_name='VK-link'),
        ),
    ]
