# Generated by Django 2.2.20 on 2021-04-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20210413_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='role',
            field=models.CharField(max_length=20, null=True, verbose_name='Роль'),
        ),
    ]
