# Generated by Django 2.2.20 on 2021-04-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_players_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='headset',
            field=models.CharField(max_length=30, null=True, verbose_name='Наушники'),
        ),
        migrations.AddField(
            model_name='players',
            name='keyboard',
            field=models.CharField(max_length=30, null=True, verbose_name='Клавиатура'),
        ),
        migrations.AddField(
            model_name='players',
            name='monitor',
            field=models.CharField(max_length=30, null=True, verbose_name='Монитор'),
        ),
        migrations.AddField(
            model_name='players',
            name='mouse',
            field=models.CharField(max_length=30, null=True, verbose_name='Мышка'),
        ),
        migrations.AddField(
            model_name='players',
            name='mousepad',
            field=models.CharField(max_length=30, null=True, verbose_name='Коврик'),
        ),
    ]
